---
name: Healthchecks Monitor
description: Pings Healthchecks at job start and finish.

branding:
  icon: check-circle
  color: blue

inputs:
  ping-url:
    description: 'Healthchecks ping URL'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
  pre: 'dist/pre/index.js'
