name: Healthchecks Monitor
description: Pings Healthchecks.io at job start and finish.
inputs:
  ping-url:
    description: 'Healthchecks base URL'
    required: true
runs:
  using: 'node16'
  pre: 'dist/pre.js'
  main: 'dist/index.js'
  post: 'dist/post.js'
